name: Run Lua Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v1
        with:
          luaVersion: '5.3'

      - name: Run Test Script
        run: |
          chmod +x tests/test_script.sh
          tests/test_script.sh
